apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - args:
    - echo "test"
    - curl -XPOST cluster-ip:port
    command:
    - /bin/sh
    - -c
    image: dominikbraun/timetrace
    name: test-pod
