apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
  - name: alpine
    image: alpine/k8s:1.24.13
    command: ["/bin/sh", "-c"]
    args:
      - "while true; do sleep 86400; done"
# must import kubeconfig!!
