apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - args:
    - timetrace version
    command:
    - /bin/sh
    - -c
    image: dominikbraun/timetrace
    name: timetrace-pod
    volumeMounts:
        - name: local-storage-claim
          mountPath: /data
  volumes:
  - name: local-storage-claim
    persistentVolumeClaim:
      claimName: local-storage-claim
