apiVersion: apps/v1
kind: Deployment
metadata:
  name: croner-wizard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: croner-wizard
  template:
    metadata:
      labels:
        app: croner-wizard
    spec:
      containers:
      - name: croner-wizard
        image: sanjin94/croner-wizard:latest
        volumeMounts:
        - name: local-storage-claim
          mountPath: /app/data
      volumes:
      - name: local-storage-claim
        persistentVolumeClaim:
          claimName: local-storage-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: croner-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: croner-main
  template:
    metadata:
      labels:
        app: croner-main
    spec:
      containers:
      - name: croner-main
        image: sanjin94/croner:latest
        env:
        - name: WIZARD_SERVICE
          value: croner-wizard-svc
        # specify in values.yaml and align
        - name: WIZARD_PORT
          value: "8081"
        volumeMounts:
        - name: local-storage-claim
          mountPath: app/data
      volumes:
      - name: local-storage-claim
        persistentVolumeClaim:
          claimName: local-storage-claim