apiVersion: apps/v1
kind: Deployment
metadata:
  name: croner-wizard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: croner-wizard
  template:
    metadata:
      labels:
        app: croner-wizard
    spec:
      containers:
      - name: croner-wizard
        image: sanjin94/croner-wizard:latest
        volumeMounts:
        - name: local-storage-claim
          mountPath: /app/data
      volumes:
      - name: local-storage-claim
        persistentVolumeClaim:
          claimName: local-storage-claim
---