apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - local
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/c/Users/u30a68/Documents/timesheet