apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
  local:
    path: C:\Users\u30a68\Documents\timesheet
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: k3s.io/hostname
          operator: In
          values:
          - hrzagwn116990

