apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
spec:
  accessModes:
  - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  volumeName: {{ .Values.persistence.pvName }}